name: CI Meson
on:
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
      - 'meson.build'
      - 'meson_options.txt'

  pull_request:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
      - 'meson.build'
      - 'meson_options.txt'

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # meson_version: ["1.2.0", "1.3.0", "1.4.0"]
        meson_version: ["1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Configure Project
        run: meson setup builddir/
      - name: Run Tests
        run: meson test -C builddir/ -v
      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
